### PR TITLE
Update rewrite branch to work with latest development version of Agda 2.5.2

### PR DESCRIPTION
**Pull request by jespercockx**

### CODE REVIEW

**Comment by jespercockx** [comment]
Note: CI is failing because these changes only work with Agda 2.5.2.

**Comment by jespercockx** [comment]
I've updated this PR after some more changes to Agda itself, and I've removed the whitespace commit. If you're okay with it I can squash my commit with a98e4c01e177be9c227d3a25c9469257b21b0296 so it looks less silly.

**Comment by favonia** [comment]
Hi @jespercockx, how about you directly manage the rewrite branch? I created this branch as an experiment to test rewriting rules, and I think you are the best person to do this. Also, I planned to rebase and merge the rewrite branch to the master branch when the newer version of Agda is out, but I would like to hear your opinions.

**Comment by jespercockx** [comment]
Ok, I'll take over the rewrite branch then until it can be merged into master (so after the release of Agda 2.5.2 probably).

**Comment by favonia** [comment]
PS: Yes I am all for squashing those two commits.

**Comment by favonia** [comment]
Let me merge and close this thread now.

**Comment by favonia** [comment]
(Please feel free to do whatever force pushing you want.)

**Pull request merged**
